// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzyrmzfgdtzaqmkhtbuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6eXJtemZnZHR6YXFta2h0YnVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NzI4NjQsImV4cCI6MjA2MjU0ODg2NH0.1UliuURMQIOPwHZVhSssNYWAihWTBtMMV-RvUuzA6bE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);